# Generated by Django 6.0.2 on 2026-02-16 10:30

from django.db import migrations, models
import django.db.models.deletion


def seed_templates(apps, schema_editor):
    ProjectTemplate = apps.get_model("users", "ProjectTemplate")
    ProjectPhase = apps.get_model("users", "ProjectPhase")
    ProjectTask = apps.get_model("users", "ProjectTask")

    templates = [
        {
            "category": "AI Projects",
            "title": "AI Project Template",
            "description": "Phases for AI-driven projects.",
            "phases": [
                {
                    "title": "Discovery",
                    "description": "Define the problem and data sources.",
                    "tasks": [
                        "Clarify the user problem and success metrics",
                        "Collect sample data and define labels",
                        "Choose baseline model and evaluation method",
                    ],
                },
                {
                    "title": "Build",
                    "description": "Train, evaluate, and iterate.",
                    "tasks": [
                        "Prepare features and train a baseline model",
                        "Evaluate performance and tune hyperparameters",
                        "Package inference into a simple API",
                    ],
                },
                {
                    "title": "Delivery",
                    "description": "Ship and monitor results.",
                    "tasks": [
                        "Create a demo UI or notebook",
                        "Document limitations and next steps",
                        "Set up basic monitoring for drift",
                    ],
                },
            ],
        },
        {
            "category": "Data Science Projects",
            "title": "Data Science Project Template",
            "description": "Phases for analytical projects.",
            "phases": [
                {
                    "title": "Discovery",
                    "description": "Frame the analysis and data plan.",
                    "tasks": [
                        "Define the business question",
                        "Inventory data sources and gaps",
                        "Create a data dictionary",
                    ],
                },
                {
                    "title": "Build",
                    "description": "Analyze and model insights.",
                    "tasks": [
                        "Clean data and explore patterns",
                        "Build metrics and dashboards",
                        "Validate findings with stakeholders",
                    ],
                },
                {
                    "title": "Delivery",
                    "description": "Communicate insights.",
                    "tasks": [
                        "Summarize key insights and actions",
                        "Publish a report or dashboard",
                        "Outline follow-up experiments",
                    ],
                },
            ],
        },
        {
            "category": "Web Development Projects",
            "title": "Web Project Template",
            "description": "Phases for web applications.",
            "phases": [
                {
                    "title": "Discovery",
                    "description": "Define features and scope.",
                    "tasks": [
                        "Write user stories and acceptance criteria",
                        "Sketch wireframes and data models",
                        "Decide on the tech stack",
                    ],
                },
                {
                    "title": "Build",
                    "description": "Implement core features.",
                    "tasks": [
                        "Build authentication and core flows",
                        "Implement CRUD for main entities",
                        "Add basic tests",
                    ],
                },
                {
                    "title": "Delivery",
                    "description": "Polish and deploy.",
                    "tasks": [
                        "Optimize UI and accessibility",
                        "Deploy to a staging environment",
                        "Write setup and usage docs",
                    ],
                },
            ],
        },
        {
            "category": "Mobile Projects",
            "title": "Mobile Project Template",
            "description": "Phases for mobile apps.",
            "phases": [
                {
                    "title": "Discovery",
                    "description": "Plan the mobile experience.",
                    "tasks": [
                        "Define app flows and screens",
                        "Plan offline and sync needs",
                        "Design data storage strategy",
                    ],
                },
                {
                    "title": "Build",
                    "description": "Implement core functionality.",
                    "tasks": [
                        "Build navigation and core screens",
                        "Add state management",
                        "Integrate notifications",
                    ],
                },
                {
                    "title": "Delivery",
                    "description": "Prepare for release.",
                    "tasks": [
                        "Test on multiple devices",
                        "Create release checklist",
                        "Document installation steps",
                    ],
                },
            ],
        },
        {
            "category": "Cloud & DevOps Projects",
            "title": "Cloud & DevOps Template",
            "description": "Phases for cloud automation projects.",
            "phases": [
                {
                    "title": "Discovery",
                    "description": "Define infrastructure needs.",
                    "tasks": [
                        "Document current architecture",
                        "Identify cost and performance goals",
                        "Choose monitoring stack",
                    ],
                },
                {
                    "title": "Build",
                    "description": "Automate and deploy.",
                    "tasks": [
                        "Provision infrastructure as code",
                        "Set up CI/CD pipelines",
                        "Configure logging and alerts",
                    ],
                },
                {
                    "title": "Delivery",
                    "description": "Harden and hand off.",
                    "tasks": [
                        "Run load and resiliency tests",
                        "Create runbooks",
                        "Review security posture",
                    ],
                },
            ],
        },
        {
            "category": "Cybersecurity Projects",
            "title": "Cybersecurity Template",
            "description": "Phases for security projects.",
            "phases": [
                {
                    "title": "Discovery",
                    "description": "Define threats and scope.",
                    "tasks": [
                        "Identify threat model",
                        "Define assets and boundaries",
                        "Select logging sources",
                    ],
                },
                {
                    "title": "Build",
                    "description": "Implement detection or protection.",
                    "tasks": [
                        "Build detection rules",
                        "Test with sample attack data",
                        "Automate alert triage",
                    ],
                },
                {
                    "title": "Delivery",
                    "description": "Operationalize.",
                    "tasks": [
                        "Document incident response steps",
                        "Create dashboards for monitoring",
                        "Plan periodic reviews",
                    ],
                },
            ],
        },
        {
            "category": "Default",
            "title": "General Project Template",
            "description": "Fallback phases for any project.",
            "phases": [
                {
                    "title": "Discovery",
                    "description": "Define scope and goals.",
                    "tasks": [
                        "Clarify project goals",
                        "List required features",
                        "Outline success criteria",
                    ],
                },
                {
                    "title": "Build",
                    "description": "Implement core features.",
                    "tasks": [
                        "Build the main workflow",
                        "Test core functionality",
                        "Refine based on feedback",
                    ],
                },
                {
                    "title": "Delivery",
                    "description": "Finalize and share.",
                    "tasks": [
                        "Write documentation",
                        "Prepare a demo",
                        "Plan next iterations",
                    ],
                },
            ],
        },
    ]

    for template_data in templates:
        template, _ = ProjectTemplate.objects.get_or_create(
            category=template_data["category"],
            defaults={
                "title": template_data["title"],
                "description": template_data["description"],
            },
        )
        if template.phases.exists():
            continue
        for phase_index, phase_data in enumerate(template_data["phases"], start=1):
            phase = ProjectPhase.objects.create(
                template=template,
                title=phase_data["title"],
                description=phase_data["description"],
                order=phase_index,
            )
            for task_index, task_text in enumerate(phase_data["tasks"], start=1):
                ProjectTask.objects.create(
                    phase=phase,
                    description=task_text,
                    order=task_index,
                )


def clear_templates(apps, schema_editor):
    ProjectTemplate = apps.get_model("users", "ProjectTemplate")
    ProjectTemplate.objects.filter(category__in=[
        "AI Projects",
        "Data Science Projects",
        "Web Development Projects",
        "Mobile Projects",
        "Cloud & DevOps Projects",
        "Cybersecurity Projects",
        "Default",
    ]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="phases", to="users.projecttemplate")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                ("phase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="users.projectphase")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(seed_templates, clear_templates),
    ]