# Generated by Django 6.0.2 on 2026-02-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('step_by_step', 'Step-by-step'), ('hands_on', 'Hands-on'), ('visual_examples', 'Visual + examples'), ('short_lessons', 'Short lessons + practice'), ('guided_checklist', 'Guided checklist')], max_length=100, null=True),
        ),
    ]
